# Generated by Django 3.1.5 on 2021-12-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ceated_at',
            new_name='created_at',
        ),
    ]
